version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          TZ: "America/New_York"
    working_directory: ~/repo
    environment:
      TZ: "America/New_York"
    context:
      - Nexus-user-circleci

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-dependencies-open_rack_vent-3.10-{{ checksum "poetry.lock" }}-{{ checksum "pyproject.toml" }}
            # fallback to using the latest cache if no exact match is found
            - v0-dependencies-open_rack_vent-

      - run:
          name: Install Dependencies
          command: |
            python3.10 -m pip install -U poetry
            python3.10 -m venv .venv
            source ./.venv/bin/activate
            poetry config virtualenvs.path ~/repo
            poetry config http-basic.nexus "${NEXUS_USERNAME}" "${NEXUS_PASSWORD}"
            # This is so stupid https://github.com/python-poetry/poetry/issues/7184
            poetry install --sync --no-ansi

      - save_cache:
          paths:
            - ./.venv
          key: v0-dependencies-open_rack_vent-{{ checksum "poetry.lock" }}-{{ checksum "pyproject.toml" }}

      - run:
          name: Run Tests
          command: |
            ./tools/run_tests.sh 'not integration'

      - run:
          name: Run Pylint
          command: |
            ./tools/run_pylint.sh

      - run:
          name: Run Black
          command: |
            ./tools/run_black.sh

      - run:
          name: Run Isort
          command: |
            ./tools/run_isort.sh

      - run:
          name: Run Mypy
          command: |
            ./tools/run_mypy.sh


